image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
stages:
  - deploy
deploy to staging:
  stage: deploy
  environment: staging
  only:
    - master
  script:
    - echo "Running web_content Upload"
    - aws --region $AWS_DEFAULT_REGION s3 cp ./web_content s3://$S3_BUCKET/ --recursive
    - echo "Content Upload is successful"
#    - 'aws autoscaling start-instance-refresh --auto-scaling-group-name $ASG_NAME --preferences '{"InstanceWarmup": 60, "MinHealthyPercentage": 50}''
    - echo "Completed the deployment workflow"
